yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='create_post'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow', views.profile_unfollow,
         name='profile_unfollow'),

]

yatube/yatube/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

"""yatube URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(unique=True, verbose_name='Слаг')
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name_plural = 'Группы'
        verbose_name = 'Группа'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста',
                            help_text='Текст нового поста')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               verbose_name='Автор')
    group = models.ForeignKey(Group,
                              blank=True,
                              null=True,
                              on_delete=models.SET_NULL,
                              verbose_name='Группа',
                              help_text='Группа, которой принадлежит пост')
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        default_related_name = 'posts'
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[0:15]


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             blank=True,
                             null=True,
                             on_delete=models.CASCADE,
                             verbose_name='Пост')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               verbose_name='Автор')
    text = models.TextField(verbose_name='Текст комментария')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')

    class Meta:
        default_related_name = 'comments'
        ordering = ['-created']
        verbose_name_plural = 'Комментарии'
        verbose_name = 'Комментарий'

    def __str__(self):
        return self.text[:20]


class Follow(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='follower',
                             verbose_name='Пользователь')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='following',
                               verbose_name='Автор')

    class Meta:
        constraints = models.UniqueConstraint(fields=['user', 'author'],
                                              name='unique_follower')
        verbose_name_plural = 'Подписки'
        verbose_name = 'Подписка'

    def __str__(self):
        return f'{self.user} подписался на {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from .forms import PostForm, CommentForm
from .models import Post, Group, User, Follow
from .utils import get_paginator


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.select_related('group', 'author')
    page_obj = get_paginator(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('group', 'author')
    page_obj = get_paginator(request, posts)
    context = {
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('group')
    page_obj = get_paginator(request, posts)
    following = request.user.is_authenticated and author.following.exists()
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all
    form = CommentForm()
    context = {
        'post': post,
        'comments': comments,
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    is_edit = True
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None, files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'is_edit': is_edit,
        'form': form,
        'post': post,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = get_paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', author.username)


@login_required
def profile_unfollow(request, username):
    follower = get_object_or_404(Follow, user=request.user,
                                 author__username=username)
    follower.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% include 'includes/head.html' %}
{% block title %}
  {% if is_edit %}
    Сохранить запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock title %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Сохранить запись
            {% else %}
              Добавить запись
            {% endif %}
          </div>
          {% include 'posts/includes/form.html' %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
          </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  </div>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load static %}
{% load cache %}
{% include 'includes/head.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock title %}
{% block content %}
{% include 'posts/includes/switcher.html' with follow=True %}
  {% cache 20 follow_page page_obj.number %}
  {% for post in page_obj %}
    {% include 'includes/post.html'  %}

    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% include 'includes/head.html' %}
{% block title %}
  Записи группы {{ group.title }}
{% endblock title %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <h4>Описание группы:</h4>
  <p>{{ group.description|linebreaksbr }}</p>
  <hr>
  {% for post in page_obj %}
    {% include 'includes/post.html' %}
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% load cache %}
{% include 'includes/head.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock title %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
  {% cache 20 index_page page_obj.number %}
  {% for post in page_obj %}
    {% include 'includes/post.html' %}
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group.title }}</a>
    {% endif %}
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Пост {{ post|truncatechars:30 }}
{% endblock title %}
{% block content %}
  <main>
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group.title }}
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group.title }}</a>
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора: <span>{{ post.author.posts.count }}</span>
          </li>
          <li class="list-group-item">
            <a href={% url 'posts:profile' post.author.username %}>все посты пользователя</a>
          </li>
          {% if post.author == request.user %}
            <li class="list-group-item">
              <a href={% url 'posts:post_edit' post.pk %}>Редактировать пост</a>
            </li>
          {% endif %}
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
      </aside>
      <article class="col-12 col-md-9">
        <p>
          {{ post }}
        </p>
      </article>
      {% include 'posts/includes/comments.html' %}
    </div>

  </main>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ author.username }}
{% endblock title %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.username }} </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>
    {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
   {% endif %}
    {% for post in page_obj %}
      {% include 'includes/post_profile.html' %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
  </main>
{% endblock content %}